# Generated by Django 4.1.7 on 2023-04-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather_api', '0002_delete_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finame', models.CharField(max_length=20)),
                ('laname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('pswrd', models.CharField(max_length=50)),
            ],
        ),
    ]
